In [1]:
import pandas as pd
import numpy as np
import torch

import matplotlib.pyplot as plt
import plotly.graph_objects as go

import urllib3 # to download data directly from web

# CH4

# Vostok CH4

[Overview of Vostok data sets](https://www.ncei.noaa.gov/access/paleo-search/study/2453)  
Called "Atmospheric Methane Data"

In [2]:
# define link to data
url = "https://www.ncei.noaa.gov/pub/data/paleo/icecore/antarctica/vostok/ch4nat-noaa.txt"

# use urllib3 package to download .txt data directly from web
# Creating a PoolManager instance for sending requests.
http = urllib3.PoolManager()

# Sending a GET request and getting back response as HTTPResponse object.
resp = http.request("GET", url)

# create new (empty) text file ('w' stands for write mode)
file = open('../data/vostok/ch4/downloaded_ch4nat-noaa.txt', 'w')
# populate text file with our data
file.write(resp.data.decode('utf-8-sig'))
# close file (write mode)
file.close()

# open file in read mode
file = open("../data/vostok/ch4/downloaded_ch4nat-noaa.txt", "r")


for index, line in enumerate(file):
    if not "#" in line:
        if line.split() == ['gas_ageBP', 'CH4']:
            # Initialise pd dataframe
            data = pd.DataFrame(columns = ('gas_ageBP', 'CH4'))
        else:
            data.loc[index] = [float(i) for i in line.split()]

# reset the index
data = data.reset_index(drop = True)

In [3]:
data

     gas_ageBP    CH4
0       2347.0  668.0
1       3634.0  636.0
2       3833.0  595.0
3       6225.0  588.0
4       6614.0  574.0
..         ...    ...
452   410793.0  623.0
453   412182.0  626.0
454   414080.0  653.0
455   415452.0  678.0
456   417173.0  695.0

[457 rows x 2 columns]

In [4]:
x_reg_400kyr = np.arange(start = 0, stop = 400000 + 1, step = 1000)
y_reg_400kyr = np.interp(x = x_reg_400kyr, xp = data["gas_ageBP"], fp = data["CH4"])

CH4_timeseries_400kyr_vostok = torch.flip(torch.tensor(y_reg_400kyr), dims = [0])

# Non-uniqueness

In [5]:
def affirm_uniqueness(ts):
    # Check for duplicates and add noise 
    dupes = ts.shape[0] - torch.unique(ts.to(torch.float32)).shape[0]
    print("There are ", dupes, " duplicates in the timeseries.")
    if dupes > 0:
        noise_level = 0.001
        while dupes > 0:
            ts = ts + torch.randn(ts.shape[0]) * noise_level
            # recalculate dupes
            dupes = ts.shape[0] - torch.unique(ts.to(torch.float32)).shape[0]
            print("Now we have ", dupes, " dupes.")
    return ts

In [6]:
CH4_timeseries_400kyr_vostok = affirm_uniqueness(CH4_timeseries_400kyr_vostok)

There are  3  duplicates in the timeseries.
Now we have  1  dupes.
Now we have  0  dupes.

# Export

In [7]:
torch.save(CH4_timeseries_400kyr_vostok, '../data/vostok/ch4/CH4_vostok_400kyr_timeseries.pt')

# EPICA CH4

- [see integrated README](https://www.ncei.noaa.gov/pub/data/paleo/icecore/antarctica/epica_domec/edc-ch4-2008.txt)
- format of txt file is slightly different so required different code to process

In [8]:
# define link to data
url = "https://www.ncei.noaa.gov/pub/data/paleo/icecore/antarctica/epica_domec/edc-ch4-2008.txt"

# use urllib3 package to download .txt data directly from web
# Creating a PoolManager instance for sending requests.
http = urllib3.PoolManager()

# Sending a GET request and getting back response as HTTPResponse object.
resp = http.request("GET", url)

# create new (empty) text file ('w' stands for write mode)
file = open('../data/epica/ch4/downloaded_edc-ch4-2008.txt', 'w')
# populate text file with our data
file.write(resp.data.decode('utf-8-sig'))
# close file (write mode)
file.close()

# open file in read mode
file = open("../data/epica/ch4/downloaded_edc-ch4-2008.txt", "r")

data = pd.DataFrame(columns = ('depth', 'gas_ageBP', 'CH4', '1s', 'lab'))

for index, line in enumerate(file):
    # Needs to be manual is file does not have #
    # last row is empty so stop there
    if (index > 153) & (index < 2257): 
        data.loc[index - 153] = [i for i in line.split()]

# select the two columns we need
# change integers in pandas dataframe to floats
data = data[["gas_ageBP", "CH4"]].astype('float64')

# reset the index
data = data.reset_index(drop = True)

In [9]:
data

      gas_ageBP    CH4
0          13.0  907.0
1         126.0  784.0
2         130.0  762.0
3         151.0  710.0
4         184.0  727.0
...         ...    ...
2098   794938.0  428.0
2099   796320.0  418.0
2100   797277.0  396.0
2101   798417.0  458.0
2102   799396.0  399.0

[2103 rows x 2 columns]

In [10]:
# target x at which we wan't to interpolate
x_reg = np.arange(start = 0, stop = 800000 + 1, step = 1000)

# np interpolate
y_reg = np.interp(x = x_reg, xp = data["gas_ageBP"], fp = data["CH4"])

# flip order 
CH4_EPICA_timeseries = torch.flip(torch.tensor(y_reg), dims = [0])
CH4_EPICA_timeseries

tensor([399.0000, 422.8652, 435.3211, 402.3678, 420.3155, 427.5514, 435.4229,
        465.7256, 466.0240, 492.0247, 540.1469, 554.1365, 608.1333, 708.4449,
        680.4717, 661.6810, 647.4412, 633.5771, 623.7696, 630.8615, 613.8941,
        606.6577, 679.8167, 630.6667, 617.8182, 579.0472, 563.0112, 565.9731,
        539.3027, 644.9854, 620.6402, 569.0148, 515.0449, 514.5248, 463.5833,
        530.7500, 552.0800, 525.6242, 473.9161, 461.3731, 461.4847, 427.2115,
        498.0000, 473.1584, 430.8215, 424.9292, 410.2893, 424.7521, 410.0406,
        420.1966, 398.6345, 400.0444, 397.8588, 404.9083, 415.1595, 424.5616,
        430.7525, 416.1193, 406.6991, 407.8162, 406.7811, 407.3987, 458.8766,
        556.9697, 538.5403, 528.8343, 522.9084, 524.0888, 531.8153, 538.2411,
        547.9816, 533.0272, 541.9973, 531.2774, 549.0719, 484.9968, 569.5650,
        565.7654, 518.8335, 458.9724, 405.1874, 397.7994, 402.3943, 408.5902,
        489.6716, 570.8693, 583.7051, 596.8605, 581.1219, 589.5728, 560.4293,
        537.9112, 508.6407, 537.5393, 610.0000, 597.0357, 591.1325, 600.3888,
        582.7025, 588.5855, 570.0506, 601.5385, 604.8929, 621.6232, 646.6787,
        639.0990, 614.8044, 600.7122, 569.8305, 571.2261, 554.6566, 547.0893,
        528.1493, 529.3704, 515.1266, 518.0215, 498.8873, 517.9024, 493.0211,
        487.8424, 450.1440, 497.7753, 492.6894, 465.8307, 539.7987, 555.5549,
        553.5680, 524.0014, 463.6765, 483.0000, 422.8297, 391.4910, 376.1413,
        373.7049, 379.7930, 397.1923, 413.3245, 393.4570, 390.3302, 401.1031,
        374.7227, 355.3472, 346.3056, 386.8891, 413.0391, 402.4801, 400.1610,
        406.7327, 410.6557, 413.1835, 418.5513, 425.2739, 427.1968, 428.5385,
        429.0000, 429.0000, 413.1789, 381.8013, 369.6183, 371.0268, 372.4352,
        373.0000, 373.0000, 373.0000, 368.9209, 364.2698, 362.7457, 368.6234,
        374.5012, 370.3879, 362.8550, 357.3081, 371.8430, 388.2744, 474.1457,
        529.1371, 572.9343, 630.8146, 638.7455, 608.7593, 603.6386, 603.0195,
        605.7387, 610.7638, 615.1646, 618.4181, 614.3305, 603.6584, 619.2963,
        597.8859, 586.4359, 577.9397, 564.6142, 537.4029, 533.5508, 514.5699,
        510.6117, 526.7431, 538.0028, 538.3508, 535.6086, 542.5724, 499.6794,
        461.6099, 449.2373, 475.8037, 527.0801, 502.2922, 478.2255, 447.2221,
        464.3235, 471.7838, 458.2198, 459.7990, 471.2725, 474.7397, 478.2069,
        481.6741, 487.8326, 485.8138, 519.0054, 613.7199, 599.7756, 596.9479,
        588.8930, 600.5211, 612.7812, 612.3656, 604.0150, 595.3002, 586.9953,
        589.5902, 614.9338, 623.4512, 619.2252, 582.9362, 551.3366, 531.4282,
        494.8296, 467.2432, 508.4688, 481.4312, 443.0000, 509.6067, 575.7024,
        548.3923, 501.9967, 451.0313, 483.2094, 476.3892, 466.2898, 445.1080,
        410.4427, 401.5690, 413.8949, 421.6703, 420.3829, 405.4732, 407.9505,
        393.9291, 397.0867, 413.5746, 459.4391, 495.4855, 485.3623, 451.7557,
        456.7432, 431.0079, 420.6814, 437.8134, 444.8533, 456.1226, 518.7722,
        530.3918, 539.7078, 534.9291, 519.6399, 526.1513, 532.3650, 522.7861,
        516.2468, 503.2597, 511.6417, 507.6465, 479.0863, 510.3913, 494.6907,
        486.9123, 486.9001, 501.3503, 527.3951, 554.0554, 580.5524, 588.8192,
        580.5101, 533.6444, 553.9111, 515.0963, 518.8363, 514.8086, 496.0728,
        502.6849, 506.9032, 516.0813, 519.1331, 502.0852, 515.4943, 500.2093,
        517.3734, 573.0464, 562.7196, 606.6559, 615.8493, 583.0000, 574.3686,
        545.6098, 540.4198, 513.1312, 505.5701, 496.7607, 510.1200, 506.3472,
        517.8734, 519.7774, 506.8421, 482.3878, 461.8544, 445.7099, 465.9290,
        482.0000, 464.4314, 437.7277, 462.9730, 488.5517, 453.5767, 444.8288,
        455.6622, 486.3108, 472.6133, 457.0735, 407.6131, 398.9448, 404.0736,
        409.2003, 412.3139, 448.7292, 483.5516, 418.0392, 399.5565, 383.7452,
        381.2220, 386.9608, 413.3426, 498.0190, 458.4088, 415.2621, 476.1884,
        438.9437, 438.1041, 410.3980, 404.2505, 396.4426, 393.6727, 389.4937,
        383.3868, 381.0000, 382.0872, 391.8183, 389.2232, 389.5909, 380.2705,
        430.7966, 426.6703, 463.9510, 460.3261, 570.2899, 611.2923, 661.1649,
        687.1648, 700.6808, 681.1342, 657.3109, 645.1316, 633.8395, 622.5595,
        644.3202, 695.5924, 656.4144, 710.3503, 696.7708, 710.8924, 713.4800,
        684.1771, 713.8223, 706.3812, 662.9477, 666.8045, 646.5895, 642.9291,
        627.9412, 607.0000, 593.7059, 606.9275, 593.0353, 595.0199, 587.5543,
        554.7324, 489.7609, 488.7635, 505.1921, 552.0921, 468.6811, 459.0979,
        564.5133, 593.1176, 558.7681, 548.4135, 504.7076, 599.9358, 544.9786,
        518.6230, 490.5411, 461.4746, 443.5865, 431.8672, 426.0000, 445.8832,
        523.4094, 510.8088, 494.5761, 516.5690, 431.8362, 426.3733, 417.7160,
        430.4102, 420.0189, 433.3806, 483.1429, 457.2955, 418.4344, 447.3585,
        417.6783, 428.2078, 430.7826, 407.8187, 403.9193, 397.4798, 401.9167,
        401.3698, 408.7299, 395.0802, 456.9977, 411.2991, 408.1007, 389.6911,
        371.5737, 373.5522, 368.8786, 390.1446, 417.3876, 451.8413, 460.2621,
        457.8515, 492.2916, 527.1972, 581.3906, 619.6689, 788.9730, 713.5581,
        636.7423, 648.3226, 649.5172, 658.0761, 643.3317, 633.6757, 617.0643,
        573.2430, 542.5574, 526.3669, 520.2486, 490.0000, 478.7388, 478.4856,
        467.4324, 622.3840, 608.8421, 555.9517, 542.0155, 515.7302, 471.0455,
        460.6918, 487.7423, 469.7557, 480.0422, 449.0396, 497.3461, 485.1312,
        463.0411, 453.0000, 469.0090, 511.0104, 518.4596, 472.5000, 491.6364,
        576.9933, 516.7692, 514.5808, 455.7211, 448.8056, 469.1084, 536.1893,
        531.0670, 518.0502, 513.5607, 491.4726, 461.1543, 507.3789, 458.4199,
        464.5784, 458.3374, 458.1029, 429.3433, 454.2148, 455.5480, 488.8655,
        470.1055, 466.5556, 460.6444, 451.1765, 453.7591, 453.5630, 433.4711,
        421.6735, 418.6492, 419.6316, 414.8312, 415.2395, 499.3864, 447.9460,
        453.7542, 452.0809, 477.4588, 480.0444, 479.5558, 450.7485, 426.4741,
        425.8049, 400.4340, 397.2165, 421.4065, 411.6864, 439.6524, 536.7797,
        530.7090, 479.1294, 507.9130, 536.6481, 541.2719, 690.6667, 622.4545,
        593.4516, 562.0891, 556.5547, 553.2414, 496.0663, 493.5319, 428.1673,
        421.7226, 431.1443, 421.7168, 486.9474, 471.3636, 499.1114, 520.2458,
        549.5543, 519.9761, 496.0345, 531.6231, 505.1881, 488.4643, 490.6724,
        472.8806, 457.0673, 451.0796, 461.0144, 564.2682, 589.0948, 576.8375,
        579.5882, 582.0135, 562.9523, 524.6977, 508.1517, 503.2459, 501.2196,
        488.4653, 481.6408, 459.1875, 490.2560, 534.2152, 569.6854, 659.1749,
        596.4934, 583.2385, 545.0822, 525.3002, 474.3248, 497.7530, 508.7871,
        470.9137, 455.0426, 423.0875, 457.4894, 438.5714, 450.7285, 472.4172,
        521.6098, 530.2122, 515.6784, 495.8573, 476.9984, 479.1839, 520.2488,
        548.6950, 497.6090, 468.8322, 446.9096, 451.4908, 451.6611, 482.3890,
        446.3967, 477.9352, 495.9789, 481.5523, 440.4038, 414.1169, 392.5930,
        412.7803, 424.4689, 417.4808, 414.8797, 439.8619, 409.9828, 414.6327,
        401.1315, 385.3160, 401.5635, 408.6750, 423.7647, 421.0542, 413.5143,
        431.4375, 467.8914, 420.1415, 401.4937, 379.7009, 401.0000, 380.1501,
        365.2623, 348.0575, 357.1517, 383.6418, 398.1503, 380.3964, 391.3480,
        410.6175, 428.3160, 456.2424, 457.5563, 490.1513, 512.1610, 535.8977,
        709.4457, 646.6897, 652.4330, 640.4171, 614.0718, 607.0000, 608.5047,
        599.2260, 572.9298, 580.6029, 545.4909, 537.1304, 496.6846, 472.0147,
        471.3972, 465.0262, 455.9540, 494.7339, 502.0623, 506.5845, 469.4550,
        464.3701, 600.8310, 596.6581, 568.4069, 484.0000, 492.3293, 543.6333,
        530.0000, 526.0000, 508.2222, 494.2819, 484.2366, 441.0513, 438.5914,
        438.3989, 439.3684, 436.3116, 448.8499, 494.0000, 503.9800, 446.0288,
        433.8626, 444.7930, 464.8893, 630.3333, 606.8166, 574.0146, 547.6609,
        513.1314, 469.0755, 465.5385, 426.5799, 415.5472, 468.3029, 450.1550,
        440.5692, 462.9397, 485.2143, 460.1250, 454.4342, 454.7674, 447.8237,
        460.7673, 437.7400, 455.3125, 437.4204, 433.2562, 430.5272, 445.7241,
        560.7030, 549.4383, 506.8880, 501.2835, 437.4386, 530.2619, 529.0253,
        511.7713, 483.9868, 461.5755, 444.5294, 439.5200, 498.2700, 463.2571,
        420.1639, 482.2105, 422.8306, 427.0467, 423.8235, 442.2556, 512.6776,
        538.5755, 440.0000, 513.4696, 419.7566, 425.7049, 450.6552, 393.3929,
        398.1667, 403.5841, 389.3667, 386.4744, 364.4992, 371.6368, 384.8571,
        387.2340, 355.9945, 363.0833, 374.2298, 375.6511, 371.9249, 391.9765,
        436.0526, 474.1350, 573.7458, 666.5000, 474.6964, 674.8085, 698.0270,
        666.3729, 644.4444, 626.0545, 599.5862, 561.1045, 568.5647, 580.4286,
        599.5000, 635.4066, 907.0000], dtype=torch.float64)

## Non-uniqueness

In [11]:
CH4_EPICA_timeseries = affirm_uniqueness(CH4_EPICA_timeseries)

There are  4  duplicates in the timeseries.
Now we have  0  dupes.

## Export

In [12]:
torch.save(CH4_EPICA_timeseries, '../data/epica/ch4/CH4_epica_800kyr_timeseries.pt')